### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by anina-vardanyan**

### CODE REVIEW

**Comment by anina-vardanyan** [comment]
fff

**Comment by yeva29** [comment]
Success, good job

**Comment by yeva29** [comment]
design - good 
functionality - there is no bugs
complexity - very good code
naming - easy to understand code
good things - success

**Comment by AarinaBB** [comment]
Hi,Anina! Im glad i have the opportunity to check your code and share my opinion with u!
The code has several problems with organization and structuring. Variable declarations are scattered throughout the code, and there is no clear logical sequence. 
The code is not too complicated, but it has several asynchronous operations.  It also contains the "userNotFound" function, which handles the case when the user is not found. The code does not contain complex algorithms, but it can be difficult to understand due to its unstructured nature.
Naming variables in the code may be better. Some variables have obscure names, such as "btn", "errorBox" and "text". It is better to use more descriptive variable names so that it is clear what elements they represent or what data they contain.
The code does not look coherent due to unstructured and scattered variable declarations. There is also no uniformity in the coding style, for example, there are both single-line and multi-line comments. It is better to stick to one coding style to increase the readability and understanding of the code.
In general, the code can be improved in terms of structuring, naming variables and coherence. It is recommended to revise and restructure the code so that it is easier to understand and maintain.

**Pull request closed without merging**
